import { chromium } from '@playwright/test';
import { fileURLToPath, pathToFileURL } from 'node:url';
const here = fileURLToPath(new URL('.', import.meta.url));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1760, height: 1200 }, deviceScaleFactor: 1 });
await page.goto(pathToFileURL(`${here}review-sheet.html`).href, { waitUntil: 'networkidle' });
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(400);
await page.screenshot({ path: `${here}review-sheet.png`, fullPage: true });
console.log('sheet shot');
await browser.close();
