-- =============================================================================
-- Stratos — phase 7 seed: the help centre's first articles.
--
-- GENERATED from the published site (not edited by hand here). Sources:
--   * 60 unique FAQ topics from the 8 published pages' FAQ sections
--     (68 Hungarian entries; the English and German pages are translations of
--     the same 68). Merged: 6 questions asked on both kkv.html and rolunk.html
--     with compatible answers, and 2 near-identical ones. The two pages
--     contradicted each other on how long a website takes; the owner's
--     answer of 2026-09-28 replaces both.
--   * 14 client-portal questions, answered from the portal's
--     actual behaviour; the four that needed a business decision carry the
--     owner's answers of 2026-09-28.
--
-- `on conflict (slug) do nothing`: re-running never overwrites an edit made
-- in the Portal. Run after 20261004000100_client_demos_meetings_help.sql.
-- =============================================================================

insert into help_articles (slug, question, answer, topic, alt_questions, source, status, review_note, position, updated_by) values
  ('web-branding-1', 'Mi tartozik pontosan a brandépítéshez — csak egy logót kapok?', 'Jóval több egy logónál — a teljes vizuális identitást felépítjük: logó, színvilág, betűtípusok, képi stílus és a hangnem, ahogy kommunikálsz. A logó csak a legláthatóbb darab; az érték az, hogy mindez egységes rendszerré áll össze, amit bárhol felismernek.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 10, null),
  ('web-branding-2', 'Mi a különbség egy logó és egy komplett arculat között?', 'A logó egyetlen jel, az arculat egy teljes rendszer: logó, színek, tipográfia és használati szabályok együtt, minden felületen egységesen. Ha csak logód van, a névjegyed, a weboldalad és a posztjaid könnyen három külön cégnek tűnnek.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 20, null),
  ('web-branding-3', 'Már van arculatom — érdemes újratervezni, vagy elég ráépíteni?', 'Attól függ, mennyire erős a meglévő alap. Ha van egy jól működő logód és színvilágod, sokszor elég ráépíteni és rendszerbe foglalni. Ha viszont széttartó vagy elavult, az újratervezés hosszú távon többet hoz. Az első lépés mindig egy őszinte átnézés.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 30, null),
  ('web-branding-4', 'Hogyan megy a brandépítés díjazása?', 'A brandépítés is a havidíjas modellben fut, így nem kell egyben kifizetned egy komplett arculat árát. A pontos konstrukciót mindig előre, átláthatóan tisztázzuk, meglepetések nélkül. Sok esetben a brandépítés összekapcsolható a weboldalas és marketinges szolgáltatással.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 40, null),
  ('web-branding-5', 'Mennyi idő alatt készül el egy teljes arculat, és mit kell hozzá megadnom?', 'Jellemzően néhány hét, attól függően, milyen gyorsan érkeznek a visszajelzéseid. Tőled arra van szükségünk, hogy megismerjük a vállalkozásod: kik az ügyfeleid, mi a küldetésed, mi különböztet meg.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 50, null),
  ('web-branding-6', 'Kapok-e brand guide-ot a logó, színek és betűtípusok használatáról?', 'Igen — arculati útmutató is jár hozzá, ami rögzíti a logó helyes verzióit, a pontos színkódokat, a betűtípusokat és a képi stílus szabályait. Így bárki, aki neked dolgozik, egységesen tudja használni a márkádat.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 60, null),
  ('web-branding-7', 'Miért fontos a tudatos brandépítés egy kis cégnek?', 'A jó szolgáltatás alap, de önmagában nem látszik — a brand mondja el a világnak, hogy jó vagy, még mielőtt kipróbálnának. Egy profi arculattal a nagyokkal egy szinten jelensz meg. Nem luxus, hanem az egyik legjobb befektetés abba, hogy téged válasszanak.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 70, null),
  ('web-branding-8', 'Beleszólhatok a kreatív folyamatba, vagy ti döntitek el?', 'A márka a tiéd, ezért végig közös munka — nem teszünk le eléd egy kész logót, hogy „tessék, ez lettél". Az elején megismerünk, a kulcspontokon egyeztetünk, és a visszajelzéseid alakítják az irányt.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 80, null),
  ('web-branding-9', 'Össze lesz hangolva a brand a weboldalammal és a hirdetéseimmel?', 'Épp ez a lényeg: a brand a fonál, ami mindent összeköt. Ugyanaz a csapat építi az arculatot, a weboldalt és kezeli a hirdetéseket, így ezek nem külön szigetek. A látogató ugyanazt a színvilágot, hangnemet és élményt kapja a hirdetéstől a kapcsolatfelvételig.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 90, null),
  ('web-branding-10', 'Mi történik a kész arculati fájlokkal — szabadon használhatom bárhol?', 'A kész arculat a tiéd — megkapod a szükséges fájlokat a megfelelő formátumokban, hogy bárhol használhasd: nyomdában, közösségi médiában, hirdetésen vagy a weboldaladon. Nem tartunk fogva a saját márkáddal.', 'Arculat és brand', array[]::text[], 'branding.html – GYIK (EN: en/branding.html, DE: de/branding.html)', 'published', null, 100, null),
  ('web-hirdeteskezeles-1', 'Mennyi hirdetési kerettel érdemes indulni, és ez hogyan viszonyul a kezelési díjhoz?', 'Két külön tételről van szó: a hirdetési keret, amit a Google vagy a Meta kap, és a kezelési díj, amit mi kapunk a munkáért. A legtöbb kis- és középvállalkozásnak havi 80–150 ezer forintos kerettel már érdemes indulni — ez alatt nehéz elég adatot gyűjteni az optimalizáláshoz. Az induló keretet mindig a piacodhoz és a céljaidhoz szabjuk.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 110, null),
  ('web-hirdeteskezeles-2', 'Mikor látok először eredményt?', 'A hirdetés az egyetlen csatorna, ahol lényegében a bekapcsolás napján jöhetnek az első érdeklődők. Az érdemi eredményhez viszont idő kell: az első 2–4 hét tanulási és adatgyűjtési szakasz, innentől optimalizálunk élesben. Reális elvárás, hogy 4–6 hét után már látszik a stabil irány.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 120, null),
  ('web-hirdeteskezeles-3', 'Google Ads vagy Meta hirdetés éri meg jobban a vállalkozásomnak?', 'Attól függ, hogy az ügyfeled keres-e rád, vagy neked kell megtalálnod őt. A Google Ads a keresleti csatorna: aki beírja, hogy „vízszerelő Győr”, az venni akar. A Meta a kereslet-teremtő csatorna: ott te szólítod meg a felhasználót a hírfolyamban. Sok vállalkozásnak a kettő kombinációja hozza a legjobb eredményt.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 130, null),
  ('web-hirdeteskezeles-4', 'Honnan tudom, hogy megtérül a hirdetés — mit és hogyan mértek?', 'Nem a lájkokat és a megjelenéseket nézzük, hanem az üzleti eredményt. Konverziómérést állítunk be: hány ajánlatkérés, hívás, űrlapkitöltés vagy vásárlás jött a hirdetésből, és az mennyibe került. Ezt havi riportban átlátható formában kapod meg.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 140, null),
  ('web-hirdeteskezeles-5', 'Mi történik a hirdetési fiókkal, ha felmondom a szerződést?', 'A hirdetési fiók a tiéd marad — ez nálunk alapelv. A kampányokat mindig a te saját Google Ads és Meta fiókodban építjük fel, amihez mi kezelői hozzáférést kapunk, nem fordítva. Ha bármikor elválnak útjaink, a fiók, az adatok és a felépített kampányok mind veled maradnak.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 150, null),
  ('web-hirdeteskezeles-6', 'Miért fizetek havidíjat a kezelésért, ha úgyis a Google/Meta kapja a hirdetési összeget?', 'Mert a platform csak egy eszköz — a pénzed elköltésének módja dönti el, hogy megtérül-e. Egy rosszul beállított kampány pontosan ugyanúgy elviszi a keretedet, csak eredmény nélkül. A kezelési díjért mi végezzük a valódi munkát: célközönség-kutatás, hirdetésszövegek, kreatívok, licitstratégia, folyamatos optimalizálás és mérés.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 160, null),
  ('web-hirdeteskezeles-7', 'Kell hozzá kész weboldal, vagy elég egy Facebook-oldal is?', 'Kell egy hely, ahová a hirdetés vezet, és ahol az érdeklődő döntést tud hozni. A legjobb egy erre kihegyezett landing oldal vagy jól felépített weboldal, mert ott te irányítod az élményt és tudsz mérni. Ha nincs megfelelő oldalad, nálunk a weboldal és a hirdetés egy kézben van.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 170, null),
  ('web-hirdeteskezeles-8', 'Garantáljátok, hogy megnő az ügyfélszám?', 'Konkrét ügyfélszámot vagy bevételt tisztességesen senki nem garantálhat — aki mégis ilyet ígér, ott legyél óvatos. Amit garantálunk: szakszerű beállítás, mérésen alapuló folyamatos optimalizálás, átlátható riportálás és őszinte kommunikáció.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 180, null),
  ('web-hirdeteskezeles-9', 'Ki írja a hirdetésszövegeket és készíti a kreatívokat?', 'A szövegezés és a kampányok felépítése a mi dolgunk — ez benne van a szolgáltatásban. A vizuális kreatívoknál a legjobb, ha a tényleges munkádról, termékedről kapunk anyagot, mert a hiteles, valódi kép sokszor jobban teljesít, mint a steril stockfotó. Egy jó telefonos felvétel a kész munkádról gyakran aranyat ér.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 190, null),
  ('web-hirdeteskezeles-10', 'Mi a különbség a fizetett hirdetés és a SEO között?', 'A kettő nem egymás helyettesítője, hanem kiegészítője. A hirdetés azonnal hoz forgalmat: bekapcsolod, jönnek az érdeklődők — de amint elzárod a csapot, elapad. A SEO lassabban épül, hónapok munkája, viszont utána tartósan, hirdetési költség nélkül hozza az ügyfeleket. A kettő együtt a legerősebb.', 'Hirdetéskezelés', array[]::text[], 'hirdeteskezeles.html – GYIK (EN: en/ads-management.html, DE: de/werbeanzeigen.html)', 'published', null, 200, null),
  ('web-impact-program-1', 'Tényleg ingyenes?', 'Igen, teljesen. A kiválasztott szervezetek semmit nem fizetnek. Nincsenek rejtett díjak, licencköltségek vagy kötelezettségek. A dizájnt, a fejlesztést és az élesítést mi álljuk.', 'Impact Program', array[]::text[], 'impact-program.html – GYIK (EN: en/impact-program.html, DE: de/impact-programm.html)', 'published', null, 210, null),
  ('web-impact-program-2', 'Miért csináljátok ezt?', 'Mert első kézből láttuk, mennyire fontosak a rehabilitációval, mentális egészséggel és gyermekvédelemmel foglalkozó szervezetek. Megvan a szakértelmünk, hogy segítsünk, ezért segítünk.', 'Impact Program', array[]::text[], 'impact-program.html – GYIK (EN: en/impact-program.html, DE: de/impact-programm.html)', 'published', null, 220, null),
  ('web-impact-program-3', 'Ki jelentkezhet?', 'Olyan nonprofit szervezetek, amelyek valódi, mérhető társadalmi hatást hoznak létre, és nyitottak az együttműködésre. Előnyt élveznek a felépüléssel, mentális egészséggel és gyermekvédelemmel foglalkozó szervezetek.', 'Impact Program', array[]::text[], 'impact-program.html – GYIK (EN: en/impact-program.html, DE: de/impact-programm.html)', 'published', null, 230, null),
  ('web-impact-program-4', 'Hány szervezetet választotok ki?', 'Évente csak néhányat. Szándékosan tartjuk kicsiben a létszámot, hogy minden szervezet teljes figyelmet és a legmagasabb színvonalú weboldalt kapja.', 'Impact Program', array[]::text[], 'impact-program.html – GYIK (EN: en/impact-program.html, DE: de/impact-programm.html)', 'published', null, 240, null),
  ('web-impact-program-5', 'Karbantartjátok a weboldalt?', 'Minden szervezet kap kezdeti technikai támogatást az élesítés után. A hosszabb távú igényeket az egyeztetésen közösen beszéljük át.', 'Impact Program', array[]::text[], 'impact-program.html – GYIK (EN: en/impact-program.html, DE: de/impact-programm.html)', 'published', null, 250, null),
  ('web-impact-program-6', 'Meglévő weboldalt is újraterveztek?', 'Természetesen. Akár a nulláról indultok, akár egy elavult oldalt váltanátok le, modern, professzionális jelenlétet építünk az alapoktól.', 'Impact Program', array[]::text[], 'impact-program.html – GYIK (EN: en/impact-program.html, DE: de/impact-programm.html)', 'published', null, 260, null),
  ('web-keresooptimalizalas-1', 'Mennyi idő alatt látszik eredmény?', 'A technikai javítások hatása néhány héten belül megjelenhet, mert a Google újra bejárja az oldalt. A tartalomból származó elmozdulás jellemzően a harmadik-negyedik hónap környékén válik mérhetővé. Aki ennél gyorsabbat ígér, az vagy hirdetést árul SEO néven, vagy olyan módszert használ, aminek később ára lesz.', 'Keresőoptimalizálás', array[]::text[], 'keresooptimalizalas.html – GYIK (EN: en/seo-consultancy.html, DE: de/seo-betreuung.html)', 'published', null, 270, null),
  ('web-keresooptimalizalas-2', 'Garantáltok első helyet a Google-ben?', 'Nem, és senki más sem tud. Az első helyet a Google rangsorolása dönti el, ami folyamatosan változik, és amire senkinek nincs ráhatása. Amit garantálni tudunk, az a munka: mit mérünk, mit javítunk, mit írunk meg, és hogy erről havonta érthető riportot kapsz.', 'Keresőoptimalizálás', array[]::text[], 'keresooptimalizalas.html – GYIK (EN: en/seo-consultancy.html, DE: de/seo-betreuung.html)', 'published', null, 280, null),
  ('web-keresooptimalizalas-3', 'Mennyibe kerül a keresőoptimalizálás?', 'Attól függ, milyen állapotban van az oldal, és mekkora a mező, amiben versenyzel. Egy helyi szolgáltatónál lényegesen kevesebb munka kell, mint egy országos webáruháznál. A díjmentes feltárás után kapsz egy konkrét ajánlatot, benne azzal, hogy pontosan mit csinálunk az első négy hónapban.', 'Keresőoptimalizálás', array[]::text[], 'keresooptimalizalas.html – GYIK (EN: en/seo-consultancy.html, DE: de/seo-betreuung.html)', 'published', null, 290, null),
  ('web-keresooptimalizalas-4', 'Kell hozzá új weboldal?', 'Nem feltétlenül. A legtöbb meglévő oldalon van elég mozgástér ahhoz, hogy érdemes legyen elkezdeni. Ha a feltárás során kiderül, hogy az oldal szerkezete vagy sebessége miatt a munka nagy része kárba veszne, ezt megmondjuk, és inkább a weboldalt hozzuk rendbe először.', 'Keresőoptimalizálás', array[]::text[], 'keresooptimalizalas.html – GYIK (EN: en/seo-consultancy.html, DE: de/seo-betreuung.html)', 'published', null, 300, null),
  ('web-keresooptimalizalas-5', 'Mi a különbség a SEO és a Google Ads között?', 'A hirdetés azonnal hoz forgalmat, és akkor áll le, amikor kifogy a keret. A keresőoptimalizálás lassabban indul, de a megszerzett pozíció akkor is dolgozik, amikor nem költesz. A kettő nem egymás alternatívája: a Rapidkertnél párhuzamosan futottak, és külön-külön is termeltek.', 'Keresőoptimalizálás', array[]::text[], 'keresooptimalizalas.html – GYIK (EN: en/seo-consultancy.html, DE: de/seo-betreuung.html)', 'published', null, 310, null),
  ('web-keresooptimalizalas-6', 'Ha felmondom, elveszik minden?', 'Nem. Amit megírtunk és megjavítottunk, az az oldaladon marad, és tovább dolgozik. A pozíciók idővel romolhatnak, ha senki nem foglalkozik velük, de nem tűnnek el egyik napról a másikra, és semmit nem kapcsolunk le.', 'Keresőoptimalizálás', array[]::text[], 'keresooptimalizalas.html – GYIK (EN: en/seo-consultancy.html, DE: de/seo-betreuung.html)', 'published', null, 320, null),
  ('web-kkv-1', 'Mennyi idő alatt készül el egy weboldal?', 'A pontos határidőt a projekt terjedelme és a szükséges anyagok rendelkezésre állása alapján, az egyeztetés során rögzítjük.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', 'Tulajdonosi döntés, 2026-09-28 (a kkv.html és a rolunk.html eltérő szövegét váltja; a webhely GYIK-jét is ehhez kell igazítani).', 330, null),
  ('web-kkv-2', 'Miért előnyös a havidíjas konstrukció a nagy egyszeri költség helyett?', 'Így nem kell egyszerre több százezer forintos beruházást vállalnod, hanem kiszámítható, alacsonyabb havi költséggel indíthatod el az online jelenléted. A havidíj emellett a folyamatos karbantartást, tárhelyet, frissítéseket és supportot is tartalmazza, így nem érnek váratlan extra költségek.', 'Weboldal', array['Miért előnyös a havidíjas konstrukció a nagy egyszeri költségek helyett?']::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 340, null),
  ('web-kkv-3', 'Mennyire lesz testreszabott a weboldalam?', 'A weboldalad a te márkádhoz, arculatodhoz és céljaidhoz igazodva készül, nem egy sablonból dolgozunk kreatív keretek nélkül. A dizájn, a szövegezés és a funkciók is a te vállalkozásod igényei alapján kerülnek kialakításra.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 350, null),
  ('web-kkv-4', 'Később bővíthető vagy fejleszthető a rendszer?', 'Igen, a weboldal moduláris felépítésű, így új oldalakkal, funkciókkal vagy akár webshoppal is bővíthető, ahogy a vállalkozásod növekszik. Nem kell mindent az elején eldöntened, a rendszer veled együtt fejlődik.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 360, null),
  ('web-kkv-5', 'Mobiltelefonon és tableten is megfelelően működik majd az oldal?', 'Igen, minden weboldal reszponzív kialakítású, vagyis automatikusan alkalmazkodik mobiltelefonhoz, tablethez és asztali géphez egyaránt. Ezt élesítés előtt minden eszköztípuson leteszteljük.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 370, null),
  ('web-kkv-6', 'Segítetek a Google és Meta hirdetések kezelésében is?', 'Igen, kérésre a Google és Meta (Facebook/Instagram) hirdetéseid beállításában és kezelésében is tudunk segíteni, a célzástól a kampányok folyamatos optimalizálásáig. Így a weboldalad mellett a hozzá vezető forgalom is szakértő kezekben van.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 380, null),
  ('web-kkv-7', 'Kapok segítséget abban, hogy megértsem, mi hogyan működik?', 'Természetesen, nem hagyunk magadra az átadás után. Érthetően elmagyarázzuk, hogyan működik az oldalad, és a legfontosabb fogalmakat is végigvesszük, hogy magabiztosan tudj döntéseket hozni.', 'Weboldal', array['Kapok segítséget a weboldal működésének és az online marketing alapjainak megértésében?']::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 390, null),
  ('web-kkv-8', 'Hogyan követhető a weboldal és a hirdetések teljesítménye?', 'A weboldalhoz és a hirdetésekhez is átlátható statisztikákat biztosítunk, amelyekből látod a látogatottságot, a legfontosabb mutatókat és a kampányok eredményességét. Igény esetén rendszeres, közérthető riportokban is összefoglaljuk a teljesítményt.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html) · rolunk.html – GYIK (EN: en/about.html, DE: de/ueber-uns.html)', 'published', null, 400, null),
  ('web-kkv-9', 'Kié a weboldal és a domain?', 'A domain és minden tartalom a tiéd. Az oldalt mi üzemeltetjük, amíg él az előfizetés; ha felmondod, a domaint és a tartalmaidat természetesen átadjuk.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html)', 'published', null, 410, null),
  ('web-kkv-10', 'Van hűségidő vagy kötbér?', 'Nincs. A szerződés havonta mondható fel, rejtett költségek nélkül. Addig maradsz, amíg elégedett vagy a szolgáltatással.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html)', 'published', null, 420, null),
  ('web-kkv-11', 'Mit kell nekem biztosítanom a kezdéshez?', 'Elég néhány alapinformáció a vállalkozásodról, valamint szövegek és képek, ha vannak. Ha nincsenek, a megfogalmazásban és a képek kiválasztásában is segítünk, hogy ne ezen múljon az indulás.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html)', 'published', null, 430, null),
  ('web-kkv-12', 'Mi van, ha már van weboldalam?', 'Meglévő oldalt is átveszünk. Átnézzük, mi menthető belőle, és vagy megújítjuk, vagy újat építünk helyette; a tartalmaid és a domained természetesen megmaradnak.', 'Weboldal', array[]::text[], 'kkv.html – GYIK (EN: en/web-design-small-business.html, DE: de/webdesign-kmu.html)', 'published', null, 440, null),
  ('web-nagyvallalat-1', 'Milyen SLA-t és rendelkezésre állást vállaltok?', 'Az üzleti kritikusságtól függően definiálunk SLA-t: garantált rendelkezésre állást (jellemzően 99,9%), definiált reakció- és megoldási időket, valamint eszkalációs folyamatot. A pontos szinteket a szerződésben rögzítjük, és riportokban követjük.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 450, null),
  ('web-nagyvallalat-2', 'Hogyan illeszkedtek a meglévő rendszereinkhez és folyamatainkhoz?', 'A fejlesztést a meglévő infrastruktúrátokra tervezzük: ERP, CRM, SSO, fizetési és logisztikai rendszerek integrációjával. Igazodunk a belső folyamataitokhoz, a biztonsági előírásaitokhoz és a fejlesztési sztenderdjeitekhez, legyen szó cloud vagy on-premise környezetről.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 460, null),
  ('web-nagyvallalat-3', 'Hogyan kezelitek az adatbiztonságot és a GDPR-megfelelőséget?', 'A biztonság a tervezés része, nem utólagos réteg: hozzáférés-kezelés, titkosítás, auditnaplózás és rendszeres biztonsági tesztek. GDPR-megfelelő adatkezelést, adatfeldolgozói szerződést és igény esetén penetrációs teszteket, valamint a belső compliance-előírásaitokhoz igazodó folyamatot biztosítunk.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 470, null),
  ('web-nagyvallalat-4', 'Skálázható a megoldás több piacra és nagy terhelésre?', 'Igen. A rendszereket eleve skálázható architektúrára tervezzük: több nyelv és piac, terheléshez igazodó infrastruktúra, cache és CDN, valamint moduláris felépítés. Ahogy nőtök, a rendszer és a hozzá rendelt csapatkapacitás is együtt skálázódik.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 480, null),
  ('web-nagyvallalat-5', 'Hogyan áll fel és hogyan skálázódik a dedikált csapat?', 'A projekthez dedikált csapatot rendelünk — fejlesztők, dizájner és egy állandó projektvezető, aki a ti oldalatokon egy kapcsolattartó. A kapacitást a terheléshez igazítjuk: fel- és leskálázzuk a csapatot a roadmap és a sprintek igényei szerint.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 490, null),
  ('web-nagyvallalat-6', 'Kié a forráskód és a szellemi tulajdon?', 'A forráskód, a dokumentáció és minden szellemi termék a tiétek. A repókhoz és a környezetekhez teljes hozzáférést adunk, a folyamat átlátható, és bármikor átvehető akár a belső csapatotok által is — nincs vendor lock-in.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 500, null),
  ('web-nagyvallalat-7', 'Milyen technológiákkal dolgoztok?', 'Modern, jól támogatott stacket használunk (pl. React/Next.js, Node, TypeScript, felhő- és konténeralapú infrastruktúra), de mindig az adott feladathoz és a ti meglévő környezetetekhez választjuk a megfelelő eszközt. A cél a hosszú távon karbantartható, ipari sztenderdeket követő megoldás.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 510, null),
  ('web-nagyvallalat-8', 'Átvesztek meglévő, más által fejlesztett rendszert?', 'Igen. Először technikai auditot végzünk: átnézzük a kódot, az architektúrát és a kockázatokat, majd javaslatot teszünk a stabilizálásra, továbbfejlesztésre vagy szükség esetén a fokozatos újraépítésre. Az átvételt kontrolláltan, a működés megszakítása nélkül végezzük.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 520, null),
  ('web-nagyvallalat-9', 'Hogyan zajlik a riportálás és a projektkövetés?', 'Sprintekben dolgozunk, rendszeres demókkal és átlátható backloggal. Hozzáférést kaptok a projektkövető és a monitoring felületekhez, és rendszeres, vezetői szintre is érthető riportokban foglaljuk össze a haladást, a KPI-okat és a rendszer teljesítményét.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 530, null),
  ('web-nagyvallalat-10', 'Milyen szerződéses és elszámolási modellben dolgoztok?', 'A projekt jellegétől függően dolgozhatunk fix áras keretben, dedikált csapat (time & material) modellben vagy folyamatos üzemeltetési retainerben. A beszerzési, jogi és compliance-folyamataitokhoz igazodunk, és minden feltételt keretszerződésben rögzítünk.', 'Nagyvállalati fejlesztés', array[]::text[], 'nagyvallalat.html – GYIK (EN: en/bespoke-web-development.html, DE: de/webentwicklung-agentur.html)', 'published', null, 540, null),
  ('web-webshop-keszites-1', 'Mennyibe kerül egy webshop készítés?', 'Attól függ, hány terméked van, hány variánssal, és mihez kell kapcsolódnia. Egy néhány száz termékes bolt havidíjas konstrukcióban is mehet, egy több ezer tételes, ERP-hez kötött rendszer projektalapon árazódik. A díjmentes konzultáció után kapsz konkrét számot.', 'Webshop', array[]::text[], 'webshop-keszites.html – GYIK (EN: en/ecommerce-web-design.html, DE: de/onlineshop-erstellung.html)', 'published', null, 550, null),
  ('web-webshop-keszites-2', 'Mennyi idő alatt készül el?', 'Egy tipikus bolt hat-tíz hét a szerződéstől az élesítésig. A leghosszabb szakasz nem a fejlesztés, hanem a terméktörzs: a fotók, a leírások és a variánsok rendbetétele. Ha ez megvan, gyorsabban végzünk; ha nincs, ebben is segítünk.', 'Webshop', array[]::text[], 'webshop-keszites.html – GYIK (EN: en/ecommerce-web-design.html, DE: de/onlineshop-erstellung.html)', 'published', null, 560, null),
  ('web-webshop-keszites-3', 'Át tudtok venni egy meglévő webáruházat?', 'Igen. Először átnézzük, mi menthető belőle — a terméktörzs és a rendelési előzmény szinte mindig átvihető, a sablon és a bővítmények ritkán. Ha a meglévő rendszer működik és csak a láthatóság hiányzik, azt is megmondjuk, mielőtt bármit újraépítenénk.', 'Webshop', array[]::text[], 'webshop-keszites.html – GYIK (EN: en/ecommerce-web-design.html, DE: de/onlineshop-erstellung.html)', 'published', null, 570, null),
  ('web-webshop-keszites-4', 'Kapok hozzá adminfelületet?', 'Igen, és arra a néhány dologra szabjuk, amit ténylegesen csinálni fogsz: termék felvitele, ár- és készletmódosítás, rendeléskezelés, kuponok. Nem egy húsz menüpontos panel, amiből hármat használsz.', 'Webshop', array[]::text[], 'webshop-keszites.html – GYIK (EN: en/ecommerce-web-design.html, DE: de/onlineshop-erstellung.html)', 'published', null, 580, null),
  ('web-webshop-keszites-5', 'Ki felel a jogi megfelelésért?', 'A kötelező tartalmakat — ÁSZF, elállási tájékoztató, adatkezelés, cookie-kezelés — beépítjük, és megmondjuk, mi hiányzik. A szövegek tartalmi helyességéért viszont jogász felel, nem mi; ha nincs, szólunk időben, hogy legyen.', 'Webshop', array[]::text[], 'webshop-keszites.html – GYIK (EN: en/ecommerce-web-design.html, DE: de/onlineshop-erstellung.html)', 'published', null, 590, null),
  ('web-webshop-keszites-6', 'Mi van, ha nő a bolt?', 'Erre épül. Új nyelv, új piac, új fizetési mód vagy egy raktárintegráció később is rákerülhet, mert kódból van és nem egy sablon korlátain belül mozog. Nem kell mindent az elején eldöntened.', 'Webshop', array[]::text[], 'webshop-keszites.html – GYIK (EN: en/ecommerce-web-design.html, DE: de/onlineshop-erstellung.html)', 'published', null, 600, null),
  ('portal-hol-adom-le', 'Hol adhatom le a képeket, a logót és a szövegeket?', 'A portál „Nyersanyag leadása” menüpontjában. Ha több projekted van, először válaszd ki a projektet, majd húzd a fájlokat a kijelölt területre, vagy nyomd meg a „Fájlok kiválasztása” gombot. A leadott fájlok a projekt „Ügyféltől érkezett nyersanyagok” mappájába kerülnek; csak te és a Stratos látja őket, más ügyfél nem.', 'Ügyfélportál – feltöltés', array['hova töltsem fel a fájlokat', 'hol tudok feltölteni', 'hogyan küldöm el a logót', 'képek feltöltése', 'szöveg leadása', 'anyagok leadása', 'nyersanyag']::text[], 'features/client/ClientApp.tsx (Nyersanyag leadása), 20261001000100_client_portal.sql', 'published', null, 610, null),
  ('portal-fajltipusok', 'Milyen fájlokat tölthetek fel?', 'Fájlonként legfeljebb 50 MB. Elfogadott típusok: PDF, Word/Excel/PowerPoint, szöveg és CSV, képek (PNG, JPG, GIF, WebP, TIFF, HEIC, SVG), PSD/AI/EPS, MP4/MOV/MP3 és ZIP. A fájlt a tartalma alapján ellenőrizzük, ezért egy átnevezett fájl (például .exe .pdf-re átírva) nem tölthető fel. Egyszerre legfeljebb 10 feltöltés lehet folyamatban, naponta legfeljebb 200 fájl és 2 GB. Vírusellenőrzés nincs.', 'Ügyfélportál – feltöltés', array['mekkora fájlt tölthetek fel', 'mi a maximális méret', 'milyen formátum', 'elfogadott fájltípusok', 'feltölthetek videót', 'zip feltöltés', 'túl nagy a fájl']::text[], 'lib/documentRules.ts, lib/clientPortal.ts (CLIENT_ALLOWED_SUMMARY), client_upload_limits()', 'published', null, 620, null),
  ('portal-javitott-valtozat', 'Hogyan adhatok le egy javított változatot?', 'Töltsd fel az új változatot új fájlként a „Nyersanyag leadása” menüpontban. Egy már leadott fájlt nem lehet törölni, átnevezni vagy felülírni; ha ugyanazzal a névvel töltesz fel, a portál sorszámot tesz a nevéhez (például „logo (2).png”), így mindkét változat megmarad.', 'Ügyfélportál – feltöltés', array['felülírhatom a feltöltött fájlt', 'rossz fájlt töltöttem fel', 'törölhetem a feltöltést', 'új verzió feltöltése', 'kicserélhetem a képet', 'javított verzió küldése', 'módosított fájl leadása', 'frissített anyag', 'lecserélhetem a korábbi képet']::text[], 'features/client/ClientApp.tsx, document_free_name()', 'published', null, 630, null),
  ('portal-dokumentumok-demo', 'Hol találom a megosztott dokumentumokat és a demót?', 'A veled megosztott fájlok a „Megosztott dokumentumok” menüpontban vannak, projektenként csoportosítva; a „Letöltés” gomb egy percig érvényes letöltési linket készít. A közzétett demók a „Projektjeim” oldalon, a projekted kártyáján jelennek meg „Demó megtekintése” gombbal, amely új lapon nyitja meg a demót.', 'Ügyfélportál – dokumentumok és demó', array['hol vannak a fájlok', 'hol a demó', 'hol nézhetem meg az oldalt', 'letöltés', 'megosztott anyagok', 'demó link']::text[], 'features/client/ClientApp.tsx, 20261004000100_client_demos_meetings_help.sql', 'published', null, 640, null),
  ('portal-demo-visszajelzes', 'Hogyan jelezzek vissza a demóról?', 'A demó kártyáján az „Észrevételek” gombbal írhatsz visszajelzést a demóról. Az üzeneted a Stratos portálján jelenik meg, és a kártyán látod, mikor olvasta el. Munkanapokon 1 munkanapon belül reagálunk.', 'Ügyfélportál – dokumentumok és demó', array['visszajelzés a demóra', 'hogyan küldjek észrevételt', 'tetszik a demó mit tegyek', 'hibát találtam a demóban', 'módosítást kérek a demón', 'észrevételek', 'hova írjam a véleményem a demóról']::text[], 'nincs hiteles forrás a folyamatra', 'published', 'Tulajdonosi döntés, 2026-09-28; a funkció: 20261005000100_client_feedback_reschedule.sql.', 650, null),
  ('portal-kovetkezo-megbeszeles', 'Hol látom a következő megbeszélést?', 'A „Projektjeim” oldalon, a projekted kártyáján. A legközelebbi, le nem mondott időpont kiemelten látszik, alatta a további jövőbeli időpontok. A lemondott megbeszélés „Lemondva” jelölést kap. A múltbeli időpontok nem jelennek meg.', 'Ügyfélportál – megbeszélések', array['mikor lesz a következő találkozó', 'hol az időpont', 'megbeszélés időpontja', 'következő meeting', 'mikor egyeztetünk']::text[], 'features/client/ClientApp.tsx, client_portal_meetings()', 'published', null, 660, null),
  ('portal-naptarba', 'Hogyan tehetem be a naptáramba?', 'A megbeszélés mellett a „Google Naptárba helyezés” gomb új lapon megnyitja a Google Naptár eseménylétrehozó oldalát, a cím, a kezdés, a befejezés, a helyszín vagy a csatlakozási link és a leírás kitöltve; csak mentened kell. Fontos: ha az időpont később a portálon módosul, a korábban elmentett naptárbejegyzés nem frissül magától – a módosítás után mentsd el újra, és a régit töröld.', 'Ügyfélportál – megbeszélések', array['google naptár', 'naptárba mentés', 'emlékeztető a megbeszélésről', 'hogyan mentsem el az időpontot', 'calendar']::text[], 'lib/meetings.ts (googleCalendarUrl)', 'published', null, 670, null),
  ('portal-masik-idopont', 'Hogyan kérhetek másik időpontot?', 'A megbeszélés kártyáján az „Új időpont javaslása” gombbal adhatsz meg másik időpontot, üzenettel együtt. A javaslat a Stratoshoz kerül: ha elfogadjuk, a megbeszélés a portálon az új időpontra módosul; ha nem, a kártyán látod a választ. Amíg a javaslatod függőben van, visszavonhatod. Munkanapokon 1 munkanapon belül reagálunk. A korábban naptárba mentett időpontot az elfogadás után mentsd el újra.', 'Ügyfélportál – megbeszélések', array['nem jó az időpont', 'áttehetjük a megbeszélést', 'időpont módosítása', 'lemondom a találkozót', 'másik nap', 'új időpontot javaslok', 'módosíthatom az időpontot']::text[], 'nincs hiteles forrás a folyamatra', 'published', 'Tulajdonosi döntés, 2026-09-28; a funkció: 20261005000100_client_feedback_reschedule.sql.', 680, null),
  ('portal-belepes', 'Mit tegyek, ha nem tudok belépni?', 'A belépési oldalon válaszd a „Forgotten your password?” linket, add meg az e-mail-címedet, és a kapott levélben lévő linkkel új jelszót állíthatsz be (legalább 12 karakter). Ha a meghívólinked nem működik (lejárt vagy már felhasználták), kérj újat a Stratostól: a meghívólink egyszer használható és korlátozott ideig érvényes.', 'Ügyfélportál – belépés és hibák', array['elfelejtettem a jelszót', 'nem tudok bejelentkezni', 'lejárt a link', 'jelszó visszaállítás', 'nem működik a meghívó']::text[], 'features/auth/pages.tsx, features/client/AcceptInvite.tsx, Auth-beállítások (PORTAL_RELEASE.md §6)', 'published', null, 690, null),
  ('portal-feltoltes-hiba', 'Mit tegyek, ha nem sikerül a feltöltés?', 'A portál minden fájlnál kiírja a hiba okát. Ha a fájl túl nagy (50 MB felett) vagy a típusa nem engedélyezett, más formátumban vagy tömörítve próbáld. Hálózati hiba esetén a fájl mellett megjelenő „Újra” gombbal újraindíthatod; a félbeszakadt feltöltés nem kerül a leadott fájlok közé. Ha a hiba szerint nincs hozzáférésed a projekthez, keresd a Stratost.', 'Ügyfélportál – belépés és hibák', array['nem tölt fel', 'hiba a feltöltésnél', 'elakadt a feltöltés', 'sikertelen feltöltés', 'nincs hozzáférésem']::text[], 'lib/clientPortal.ts (CLIENT_UPLOAD_TEXT), lib/documents.ts (useUploader)', 'published', null, 700, null),
  ('portal-tovabbi-modositas', 'Hogyan kérhetek további módosítást vagy átadás utáni segítséget?', 'A módosítási körök száma a szerződésedben található. A további módosítás díja a módosítás mértékétől függ. Karbantartásra projekttől függően havidíjas árat adunk. Írj nekünk (lukacs.artur@media-stratos.com, +36 30 584 8024); munkanapokon 1 munkanapon belül válaszolunk.', 'Ügyfélportál – módosítás és támogatás', array['további módosítás', 'változtatást szeretnék', 'átadás után segítség', 'karbantartás', 'hány módosítási kör van', 'garancia']::text[], 'nincs hiteles forrás', 'published', 'Tulajdonosi döntés, 2026-09-28.', 710, null),
  ('portal-ki-latja', 'Ki látja a feltöltött és a velem megosztott fájlokat?', 'A te feltöltéseidet csak te és a Stratos látja; ugyanazon a projekten dolgozó más ügyfél sem. A megosztott fájlt csak az látja, akivel megosztották. Ha a projekthez való hozzáférésedet visszavonják, a projekt, a megosztások, a demók és a megbeszélések is eltűnnek a portálodról.', 'Ügyfélportál – dokumentumok és demó', array['láthatja más a fájljaimat', 'biztonságos a feltöltés', 'ki fér hozzá', 'adatvédelem']::text[], '20261001000100_client_portal.sql (client_portal_* függvények)', 'published', null, 720, null),
  ('portal-demo-nyilvanos', 'Csak én látom a demóoldalt?', 'A portálon csak a projektedhez rendelt fiókok látják a demó linkjét, de maga a demóoldal a portálon kívül fut: aki ismeri a címét, az meg tudja nyitni. Ezért a demó linkjét ne add tovább olyannak, akinek nem szánod.', 'Ügyfélportál – dokumentumok és demó', array['privát a demó', 'megoszthatom a demót', 'jelszóval védett a demó', 'ki látja a demót']::text[], '20261004000100_client_demos_meetings_help.sql (fejléc)', 'published', null, 730, null),
  ('portal-projekt-allapot', 'Hol látom a projekt állapotát, határidejét vagy a fizetéseket?', 'A portál ügyféloldalán nincs projektállapot, határidő vagy pénzügyi információ: itt a megosztott dokumentumokat, a közzétett demókat, a következő megbeszéléseket és a saját feltöltéseidet látod. A projekt állásáról a Stratos kapcsolattartódtól kérdezz.', 'Ügyfélportál – módosítás és támogatás', array['hol tart a projekt', 'mikor lesz kész', 'határidő', 'számla', 'fizetés', 'mennyit fizettem', 'projekt állapota']::text[], 'client_portal_* függvények (nincs állapot- vagy pénzügyi mező)', 'published', null, 740, null)
on conflict (slug) do nothing;
