-- =============================================================================
-- Stratos — phase 3: the owner's private document library
--
-- One document system, per project, for paid and Impact projects alike. The
-- Documents screen and the project screen read the same rows and the same
-- stored objects; there is no second copy anywhere.
--
--   1. limits          `document_max_bytes()` — one number, used by the bucket,
--                      the upload start and the completion check
--   2. the bucket      `project-documents`, private, size-limited
--   3. folders         `document_folders`: a tree per project, no cycles, no
--                      parent in another project
--   4. documents       `project_documents`: one row per file; the stored object
--                      lives at `<project id>/<document id>` and nowhere else
--   5. row rules       the upload lifecycle (pending → ready | failed), which is
--                      only allowed to reach `ready` when the stored object is
--                      really there at the declared size
--   6. operations      start an upload, finish it, move, trash, restore — each
--                      a SECURITY INVOKER function, so RLS decides
--   7. maintenance     reconcile stale uploads; report orphans. Report, never
--                      delete.
--   8. access          owner-only on the tables AND on storage.objects, with
--                      restrictive guards so no other storage policy can open
--                      this bucket to anyone else
--
-- WHY THE STORAGE PATH IS TWO IDS
-- -------------------------------
-- A name is something a person changes; an id is not. The object key is
-- `<project_id>/<document_id>`, generated by the database, so renaming a file,
-- renaming a folder or moving a file between folders is an UPDATE of one row
-- and never a copy of bytes. A document cannot move to another project (its
-- project id is fixed), so the key never has to change.
--
-- WHAT THIS DOES NOT DO
-- ---------------------
-- No permanent deletion anywhere: no DELETE grant on either table, no DELETE or
-- UPDATE policy on this bucket's objects, and a restrictive guard that refuses
-- both even if another policy would allow them. "Delete" is the trash, which is
-- reversible — and trashed files STILL OCCUPY STORAGE until someone removes
-- them by hand from the Supabase dashboard (supabase/DOCUMENTS.md §6).
--
-- No client accounts, sharing or client uploads (the next phase). The model
-- leaves room for them — every row is keyed by id and records who uploaded it —
-- without building any of it.
--
-- `media_assets` (20260801000100) is an older, unused scaffold with no bucket
-- and no screen. It is left untouched and is NOT this library.
--
-- Run after the owner lockdown (20260928000300) and the Impact programme
-- (20260929000300). Refuses to run otherwise — see §0.
-- =============================================================================


-- ###########################################################################
-- 0. PRECONDITIONS
-- ###########################################################################

do $$
declare
  owner_role user_role;
begin
  select p.role into owner_role
  from portal_owner o join profiles p on p.id = o.user_id;
  if owner_role is distinct from 'super_admin' then
    raise exception 'No portal owner who is a super_admin is designated. Apply the owner tracker and portal_set_owner() first.';
  end if;

  -- Documents follow the project: if projects are not yet owner-only, neither
  -- would the list of which files exist for which client be.
  if not exists (select 1 from pg_policies
                 where schemaname = 'public' and tablename = 'projects' and policyname = 'projects_owner_all') then
    raise exception 'The owner lockdown (20260928000300_owner_lockdown.sql) is not applied.';
  end if;

  if not exists (select 1 from information_schema.columns
                 where table_schema = 'public' and table_name = 'projects' and column_name = 'program') then
    raise exception 'projects.program is missing. Apply the Impact programme (20260929000300_impact_program.sql) first.';
  end if;

  if to_regclass('storage.objects') is null or to_regclass('storage.buckets') is null then
    raise exception 'Supabase Storage (storage.objects, storage.buckets) is not present in this database.';
  end if;
end $$;


-- ###########################################################################
-- 1. LIMITS
-- ###########################################################################

-- 50 MiB, the largest single upload the Supabase Free plan accepts. Raising it
-- is a change here (and a plan that allows it); the bucket, the upload start
-- and the completion check all read this one function.
create or replace function document_max_bytes() returns bigint
  language sql immutable as $$ select 52428800::bigint $$;

-- How long an upload may stay `pending` before `document_reconcile()` calls it
-- expired. Longer than the signed upload URL can live on the hosted project
-- (2 hours, per the Supabase client documentation — the client cannot choose
-- it), so a pending row is never expired while its URL could still be used.
create or replace function document_pending_ttl() returns interval
  language sql immutable as $$ select interval '3 hours' $$;

create or replace function document_bucket() returns text
  language sql immutable as $$ select 'project-documents'::text $$;

-- A name as a person sees it. Never part of a storage key, but still shown in
-- the Portal and sent as a download file name, so no path separators, no
-- control characters, no surrounding space.
create or replace function document_name_valid(n text) returns boolean
  language sql immutable as $$
  select n is not null
     and n = btrim(n)
     and length(n) between 1 and 200
     and n !~ '[[:cntrl:]/\\]'
     and n not in ('.', '..')
$$;

-- THE ALLOWED FILE TYPES
-- ----------------------
-- A file is accepted only if its extension is on this list AND the content
-- kind detected from its first bytes is one this extension may carry. The list
-- is what a web/brand/ads studio exchanges with its clients; anything else —
-- executables, scripts, HTML, archives other than ZIP — is refused.
--
-- The content kind is detected IN THE BROWSER from the file's own bytes
-- (portal/src/lib/documentRules.ts → `sniffKind`) and stored with the row. The
-- database cannot read an object's bytes, so it cannot re-check them; what it
-- enforces is that a row's name and its recorded kind agree, on insert and on
-- every rename. For the owner-only library this stops mistakes and disguised
-- files that arrive from outside (a `.pdf` that is really HTML). It is NOT a
-- defence against the owner's own API calls, and it is not a virus scan: see
-- supabase/DOCUMENTS.md §3.
--
-- Kept in step with ALLOWED_TYPES in documentRules.ts by
-- tests/portal-documents-db.spec.ts → "the allowlist is the same list".
create or replace function document_extension(n text) returns text
  language sql immutable as $$ select lower(substring(n from '\.([A-Za-z0-9]{1,8})$')) $$;

create or replace function document_kinds_for(ext text) returns text[]
  language sql immutable as $$
  select case ext
    when 'pdf'  then array['pdf']
    when 'ai'   then array['pdf', 'postscript']
    when 'eps'  then array['postscript']
    when 'png'  then array['png']
    when 'jpg'  then array['jpeg']
    when 'jpeg' then array['jpeg']
    when 'gif'  then array['gif']
    when 'webp' then array['webp']
    when 'tif'  then array['tiff']
    when 'tiff' then array['tiff']
    when 'heic' then array['isobmff']
    when 'psd'  then array['psd']
    when 'svg'  then array['svg']
    when 'docx' then array['zip']
    when 'xlsx' then array['zip']
    when 'pptx' then array['zip']
    when 'odt'  then array['zip']
    when 'ods'  then array['zip']
    when 'odp'  then array['zip']
    when 'zip'  then array['zip']
    when 'doc'  then array['ole']
    when 'xls'  then array['ole']
    when 'ppt'  then array['ole']
    when 'rtf'  then array['rtf']
    when 'txt'  then array['text']
    when 'csv'  then array['text']
    when 'md'   then array['text']
    when 'mp4'  then array['isobmff']
    when 'mov'  then array['isobmff']
    when 'm4a'  then array['isobmff']
    when 'mp3'  then array['mp3']
  end
$$;

create or replace function document_type_allowed(n text, kind text) returns boolean
  language sql immutable as $$
  select coalesce(kind = any (document_kinds_for(document_extension(n))), false)
$$;


-- ###########################################################################
-- 2. THE BUCKET
-- ###########################################################################

-- Private (`public = false`): no object in it has a public URL. Every read is a
-- policy-checked request or a short-lived signed URL. Re-running this file
-- forces it back to private and back to the limit, whatever was changed by hand.
--
-- `allowed_mime_types` is ONLY application/octet-stream. Storage checks an
-- upload's Content-Type against this list itself, so no object in this bucket
-- can ever be stored as text/html, image/svg+xml or anything else a browser
-- would render: every download is bytes, served as an attachment. The real
-- type is decided from the file's content (document_kinds_for, above) and kept on the row.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (document_bucket(), document_bucket(), false, document_max_bytes(), array['application/octet-stream'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;


-- ###########################################################################
-- 3. FOLDERS
-- ###########################################################################

-- The project itself is the top folder; a row here is a folder INSIDE it.
-- `parent_id` null = directly under the project.
create table if not exists document_folders (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid not null references projects(id) on delete restrict,
  parent_id     uuid,
  name          text not null check (document_name_valid(name)),
  created_by    uuid references profiles(id) on delete set null default auth.uid(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  trashed_at    timestamptz,
  -- The folder whose trashing took this one with it. Null when trashed on its
  -- own (or not trashed). Restoring that folder restores exactly these.
  trashed_with  uuid,
  unique (project_id, id),
  -- A parent in ANOTHER project is not a thing that can be written: the key
  -- includes the project.
  foreign key (project_id, parent_id) references document_folders (project_id, id),
  check (parent_id is distinct from id),
  check (trashed_with is null or trashed_at is not null)
);

comment on table document_folders is
  'Folders inside a project''s document library. Owner-only. Names are display only; storage keys never contain them.';

-- One live folder of a name per parent (case-insensitive). The zero uuid
-- stands for "directly under the project", which a plain unique index would
-- treat as distinct nulls.
create unique index if not exists document_folders_sibling_name
  on document_folders (project_id, coalesce(parent_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(name))
  where trashed_at is null;
create index if not exists document_folders_project_idx on document_folders (project_id);

drop trigger if exists document_folders_updated_at on document_folders;
create trigger document_folders_updated_at before update on document_folders
  for each row execute function set_updated_at();


-- ###########################################################################
-- 4. DOCUMENTS
-- ###########################################################################

create table if not exists project_documents (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid not null references projects(id) on delete restrict,
  folder_id       uuid,
  name            text not null check (document_name_valid(name)),
  -- The size the browser declared when the upload started. Completion is only
  -- allowed when the stored object is exactly this size.
  byte_size       bigint not null check (byte_size >= 0),
  declared_type   text check (declared_type is null or length(declared_type) <= 200),
  -- What the file's first bytes are (see document_kinds_for). Fixed.
  content_kind    text not null,
  upload_state    text not null default 'pending'
                  check (upload_state in ('pending', 'ready', 'failed')),
  failure_reason  text check (failure_reason in
                  ('network', 'too_large', 'size_mismatch', 'expired', 'cancelled', 'storage_refused')),
  storage_path    text generated always as (project_id::text || '/' || id::text) stored,
  uploaded_by     uuid references profiles(id) on delete set null default auth.uid(),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  completed_at    timestamptz,
  trashed_at      timestamptz,
  trashed_by      uuid references profiles(id) on delete set null,
  trashed_with    uuid,
  foreign key (project_id, folder_id) references document_folders (project_id, id),
  check ((upload_state = 'failed') = (failure_reason is not null)),
  check ((upload_state = 'ready') = (completed_at is not null)),
  check (trashed_with is null or trashed_at is not null),
  -- Name and content agree, on insert and on every rename.
  constraint project_documents_type_allowed check (document_type_allowed(name, content_kind))
);

comment on table project_documents is
  'Files of the owner''s project document library. The object is at storage_path in the project-documents bucket; the name is display only.';
comment on column project_documents.storage_path is
  '<project_id>/<id>. Generated, never contains a user-supplied name, never changes.';
comment on column project_documents.trashed_at is
  'In the trash. Reversible. The stored object is NOT removed and still occupies storage.';

create unique index if not exists project_documents_storage_path_key on project_documents (storage_path);
-- Two files of the same name in one folder are refused by the database, so an
-- upload can never overwrite another document's row. Pending and failed
-- uploads hold their name too: a retry keeps it.
create unique index if not exists project_documents_sibling_name
  on project_documents (project_id, coalesce(folder_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(name))
  where trashed_at is null;
create index if not exists project_documents_project_idx on project_documents (project_id);
create index if not exists project_documents_name_idx on project_documents (lower(name));

drop trigger if exists project_documents_updated_at on project_documents;
create trigger project_documents_updated_at before update on project_documents
  for each row execute function set_updated_at();


-- ###########################################################################
-- 5. ROW RULES
-- ###########################################################################

-- Is the stored object for this path really there, at exactly this size, and
-- within the limit? Read with the caller's own rights — the owner's storage
-- policy lets them see every object in the bucket; anybody else sees none, and
-- the answer is false.
create or replace function document_object_size(p_path text) returns bigint
  language sql stable security invoker set search_path = public as $$
  select (o.metadata->>'size')::bigint
  from storage.objects o
  where o.bucket_id = document_bucket() and o.name = p_path
$$;

create or replace function document_folder_rules() returns trigger
  language plpgsql security invoker set search_path = public as $$
begin
  if tg_op = 'UPDATE' and new.project_id is distinct from old.project_id then
    raise exception 'stratos:document_project_fixed' using errcode = 'P0001',
      hint = 'A folder cannot move to another project.';
  end if;

  if new.trashed_at is null and new.parent_id is not null
     and (tg_op = 'INSERT' or new.parent_id is distinct from old.parent_id or old.trashed_at is not null)
     and exists (select 1 from document_folders f where f.id = new.parent_id and f.trashed_at is not null) then
    raise exception 'stratos:document_folder_trashed' using errcode = 'P0001',
      hint = 'That folder is in the trash. Restore it first.';
  end if;

  -- No cycles: the new parent may not be this folder or any folder under it.
  -- `union` (not `union all`) keeps the walk finite even on bad data.
  if tg_op = 'UPDATE' and new.parent_id is distinct from old.parent_id and new.parent_id is not null
     and exists (
       with recursive up as (
         select f.id, f.parent_id from document_folders f where f.id = new.parent_id
         union
         select f.id, f.parent_id from document_folders f join up on f.id = up.parent_id
       )
       select 1 from up where up.id = new.id
     ) then
    raise exception 'stratos:document_folder_cycle' using errcode = 'P0001',
      hint = 'A folder cannot be moved inside itself.';
  end if;

  if new.trashed_at is null then
    new.trashed_with := null;
  elsif tg_op = 'INSERT' then
    raise exception 'stratos:document_insert_trashed' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists document_folders_rules on document_folders;
create trigger document_folders_rules before insert or update on document_folders
  for each row execute function document_folder_rules();

-- The upload lifecycle, on the row, so it holds for the Portal and for a
-- direct PATCH alike:
--
--   insert           always `pending`, never trashed, never completed
--   pending → failed a reason is required (CHECK above)
--   failed → pending a retry; the reason is cleared
--   → ready          ONLY if the stored object exists at exactly `byte_size`
--                    and within the limit; stamps `completed_at`
--   ready → *        never. A finished document stays finished.
--
-- and the facts that never change: which project, how large, where stored.
create or replace function document_rules() returns trigger
  language plpgsql security invoker set search_path = public as $$
declare
  stored bigint;
begin
  if tg_op = 'INSERT' then
    if new.upload_state <> 'pending' or new.trashed_at is not null then
      raise exception 'stratos:document_insert_pending_only' using errcode = 'P0001',
        hint = 'A document starts as a pending upload.';
    end if;
    new.completed_at := null;
    new.failure_reason := null;
    new.uploaded_by := coalesce(auth.uid(), new.uploaded_by);
  else
    if new.project_id is distinct from old.project_id then
      raise exception 'stratos:document_project_fixed' using errcode = 'P0001',
        hint = 'A document cannot move to another project.';
    end if;
    if new.byte_size is distinct from old.byte_size or new.uploaded_by is distinct from old.uploaded_by
       or new.content_kind is distinct from old.content_kind
       or new.created_at is distinct from old.created_at then
      raise exception 'stratos:document_fact_fixed' using errcode = 'P0001';
    end if;

    if old.upload_state = 'ready' and new.upload_state <> 'ready' then
      raise exception 'stratos:document_ready_final' using errcode = 'P0001',
        hint = 'A finished upload stays finished. Upload a new file instead.';
    end if;

    if new.upload_state = 'ready' and old.upload_state <> 'ready' then
      -- Not `new.storage_path`: a generated column is not computed yet in a
      -- BEFORE trigger. Same expression as its definition.
      stored := document_object_size(new.project_id::text || '/' || new.id::text);
      if stored is null or stored <> new.byte_size or stored > document_max_bytes() then
        raise exception 'stratos:document_not_uploaded' using errcode = 'P0001',
          hint = 'The stored file is missing or does not match the upload. Finish the upload through document_finish_upload().';
      end if;
      new.completed_at := now();
    elsif new.upload_state = 'ready' then
      new.completed_at := old.completed_at;
    else
      new.completed_at := null;
    end if;

    if new.upload_state <> 'failed' then
      new.failure_reason := null;
    end if;

    -- The trash: the database stamps when and who.
    if new.trashed_at is not null and old.trashed_at is null then
      new.trashed_at := now();
      new.trashed_by := auth.uid();
    elsif new.trashed_at is null then
      new.trashed_by := null;
      new.trashed_with := null;
    end if;
  end if;

  if new.trashed_at is null and new.folder_id is not null
     and (tg_op = 'INSERT' or new.folder_id is distinct from old.folder_id or old.trashed_at is not null)
     and exists (select 1 from document_folders f where f.id = new.folder_id and f.trashed_at is not null) then
    raise exception 'stratos:document_folder_trashed' using errcode = 'P0001',
      hint = 'That folder is in the trash. Restore it first.';
  end if;

  return new;
end;
$$;

drop trigger if exists project_documents_rules on project_documents;
create trigger project_documents_rules before insert or update on project_documents
  for each row execute function document_rules();


-- ###########################################################################
-- 6. OPERATIONS
-- ###########################################################################

-- Every function below is SECURITY INVOKER: it can do nothing the caller could
-- not do with direct requests, and every row it touches is filtered by the
-- owner-only policies in §8. They exist for the steps a single request cannot
-- do safely: choose a free name under a lock, or move a folder and everything
-- in it to the trash together.

-- Serialise name choices within one project. Two uploads of "offer.pdf" at the
-- same moment would otherwise both see the name free; the second insert would
-- then fail on the unique index instead of becoming "offer (2).pdf".
create or replace function document_lock(p_project uuid) returns void
  language sql volatile security invoker as $$
  select pg_advisory_xact_lock(hashtextextended('stratos-documents:' || p_project::text, 0))
$$;

-- Make a browser-supplied file name storable: separators and control
-- characters become "_", surrounding space goes, and an over-long name is cut
-- in its stem so the extension survives.
create or replace function document_clean_name(p_name text) returns text
  language plpgsql immutable as $$
declare
  n text := btrim(regexp_replace(coalesce(p_name, ''), '[[:cntrl:]/\\]', '_', 'g'));
  ext text := coalesce(substring(n from '(\.[^.[:space:]]{1,16})$'), '');
begin
  if n in ('', '.', '..') then
    return 'file';
  end if;
  if length(n) > 200 then
    n := btrim(left(left(n, length(n) - length(ext)), 200 - length(ext))) || ext;
  end if;
  return n;
end;
$$;

-- "offer.pdf" → "offer (2).pdf" → "offer (3).pdf", within one folder, among
-- the documents (or folders) not in the trash. Call under document_lock().
create or replace function document_free_name(
  p_project uuid, p_folder uuid, p_name text, p_except uuid default null, p_kind text default 'document'
) returns text
  language plpgsql stable security invoker set search_path = public as $$
declare
  stem text;
  ext  text;
  candidate text := p_name;
  n integer := 1;
begin
  if p_kind = 'document' then
    ext := coalesce(substring(p_name from '(\.[^.[:space:]]{1,16})$'), '');
  else
    ext := '';
  end if;
  stem := left(p_name, length(p_name) - length(ext));

  loop
    exit when not (
      case when p_kind = 'document' then exists (
        select 1 from project_documents d
        where d.project_id = p_project and d.folder_id is not distinct from p_folder
          and d.trashed_at is null and lower(d.name) = lower(candidate)
          and d.id is distinct from p_except)
      else exists (
        select 1 from document_folders f
        where f.project_id = p_project and f.parent_id is not distinct from p_folder
          and f.trashed_at is null and lower(f.name) = lower(candidate)
          and f.id is distinct from p_except)
      end);
    n := n + 1;
    candidate := left(stem, 200 - length(ext) - length(n::text) - 3) || ' (' || n || ')' || ext;
  end loop;
  return candidate;
end;
$$;

-- Start an upload: a `pending` row under a free name. Returns what the browser
-- needs to ask Storage for a signed upload URL for exactly that one path.
create or replace function document_begin_upload(
  p_project uuid, p_folder uuid, p_name text, p_size bigint, p_type text default null, p_kind text default null
) returns table (id uuid, name text, storage_path text)
  language plpgsql volatile security invoker set search_path = public as $$
#variable_conflict use_column
declare
  clean text := document_clean_name(p_name);
  created project_documents;
begin
  if not is_owner() then
    raise exception 'stratos:document_owner_only' using errcode = '42501';
  end if;
  if p_size is null or p_size < 0 then
    raise exception 'stratos:document_size_unknown' using errcode = 'P0001';
  end if;
  if p_size > document_max_bytes() then
    raise exception 'stratos:document_too_large' using errcode = 'P0001',
      detail = format('%s bytes; the limit is %s.', p_size, document_max_bytes());
  end if;
  if not document_type_allowed(clean, p_kind) then
    raise exception 'stratos:document_type_not_allowed' using errcode = 'P0001',
      detail = format('extension %s, content %s', coalesce(document_extension(clean), 'none'), coalesce(p_kind, 'unknown'));
  end if;

  perform document_lock(p_project);
  insert into project_documents (project_id, folder_id, name, byte_size, declared_type, content_kind)
  values (p_project, p_folder,
          document_free_name(p_project, p_folder, clean),
          p_size, nullif(left(btrim(coalesce(p_type, '')), 200), ''), p_kind)
  returning * into created;

  return query select created.id, created.name, created.storage_path;
end;
$$;

-- Finish an upload: look at what Storage actually holds for the row's path and
-- decide. Safe to call any number of times — a repeat on a finished row just
-- answers `ready`. Returns the state after the call:
--
--   ready    the object is there at the declared size (now, or already)
--   missing  no object yet; the row is left as it was, so the upload can be
--            retried or finished later
--   failed   the object is there but too large or of the wrong size
create or replace function document_finish_upload(p_id uuid) returns text
  language plpgsql volatile security invoker set search_path = public as $$
declare
  d project_documents;
  stored bigint;
begin
  select * into d from project_documents where id = p_id for update;
  if not found then
    raise exception 'stratos:document_not_found' using errcode = 'P0002';
  end if;
  if d.upload_state = 'ready' then
    return 'ready';
  end if;

  stored := document_object_size(d.storage_path);
  if stored is null then
    return 'missing';
  end if;
  if stored > document_max_bytes() then
    update project_documents set upload_state = 'failed', failure_reason = 'too_large' where id = p_id;
    return 'failed';
  end if;
  if stored <> d.byte_size then
    update project_documents set upload_state = 'failed', failure_reason = 'size_mismatch' where id = p_id;
    return 'failed';
  end if;

  update project_documents set upload_state = 'ready' where id = p_id;
  return 'ready';
end;
$$;

-- Move a document to another folder of the same project (null = the project's
-- top level). If the target already holds that name, the moved file is
-- numbered rather than refused — the person chose a folder, not a name.
create or replace function document_move(p_id uuid, p_folder uuid) returns text
  language plpgsql volatile security invoker set search_path = public as $$
declare
  d project_documents;
  fresh text;
begin
  select * into d from project_documents where id = p_id;
  if not found then
    raise exception 'stratos:document_not_found' using errcode = 'P0002';
  end if;
  if d.folder_id is not distinct from p_folder then
    return d.name;
  end if;
  perform document_lock(d.project_id);
  fresh := document_free_name(d.project_id, p_folder, d.name, d.id);
  update project_documents set folder_id = p_folder, name = fresh where id = p_id;
  return fresh;
end;
$$;

-- Restore one folder and, first, every trashed folder above it, so the
-- restored item has somewhere to be. A name taken meanwhile is numbered.
create or replace function document_restore_folder_chain(p_folder uuid) returns void
  language plpgsql volatile security invoker set search_path = public as $$
declare
  f document_folders;
begin
  if p_folder is null then
    return;
  end if;
  select * into f from document_folders where id = p_folder;
  if not found or f.trashed_at is null then
    return;
  end if;
  perform document_restore_folder_chain(f.parent_id);
  update document_folders
     set trashed_at = null,
         name = document_free_name(f.project_id, f.parent_id, f.name, f.id, 'folder')
   where id = f.id;
end;
$$;

create or replace function document_restore(p_id uuid) returns text
  language plpgsql volatile security invoker set search_path = public as $$
declare
  d project_documents;
  fresh text;
begin
  select * into d from project_documents where id = p_id;
  if not found then
    raise exception 'stratos:document_not_found' using errcode = 'P0002';
  end if;
  if d.trashed_at is null then
    return d.name;
  end if;
  perform document_lock(d.project_id);
  perform document_restore_folder_chain(d.folder_id);
  fresh := document_free_name(d.project_id, d.folder_id, d.name, d.id);
  update project_documents set trashed_at = null, name = fresh where id = p_id;
  return fresh;
end;
$$;

-- Trash a folder and everything in it that is not already in the trash. Each
-- item taken along is marked `trashed_with` this folder, so restoring the
-- folder brings back exactly what it took — not files that were trashed on
-- their own before it.
create or replace function document_trash_folder(p_folder uuid) returns integer
  language plpgsql volatile security invoker set search_path = public as $$
declare
  f document_folders;
  moved integer;
begin
  select * into f from document_folders where id = p_folder;
  if not found then
    raise exception 'stratos:document_folder_not_found' using errcode = 'P0002';
  end if;
  if f.trashed_at is not null then
    return 0;
  end if;
  perform document_lock(f.project_id);

  with recursive tree as (
    select id from document_folders where id = p_folder
    union
    select c.id from document_folders c join tree on c.parent_id = tree.id
    where c.trashed_at is null
  )
  update project_documents
     set trashed_at = now(), trashed_with = p_folder
   where folder_id in (select id from tree) and trashed_at is null;
  get diagnostics moved = row_count;

  with recursive tree as (
    select id from document_folders where parent_id = p_folder and trashed_at is null
    union
    select c.id from document_folders c join tree on c.parent_id = tree.id
    where c.trashed_at is null
  )
  update document_folders
     set trashed_at = now(), trashed_with = p_folder
   where id in (select id from tree);

  update document_folders set trashed_at = now(), trashed_with = null where id = p_folder;
  return moved;
end;
$$;

create or replace function document_restore_folder(p_folder uuid) returns text
  language plpgsql volatile security invoker set search_path = public as $$
declare
  f document_folders;
begin
  select * into f from document_folders where id = p_folder;
  if not found then
    raise exception 'stratos:document_folder_not_found' using errcode = 'P0002';
  end if;
  perform document_lock(f.project_id);
  perform document_restore_folder_chain(p_folder);
  -- What it took with it, top down: a folder comes back only once its parent
  -- is back, so the "no live item inside a trashed folder" rule holds at every
  -- step. Their names cannot clash: nothing can be created inside a trashed
  -- folder.
  loop
    update document_folders c set trashed_at = null
     where c.trashed_with = p_folder
       and exists (select 1 from document_folders p where p.id = c.parent_id and p.trashed_at is null);
    exit when not found;
  end loop;
  update project_documents set trashed_at = null where trashed_with = p_folder;
  return (select name from document_folders where id = p_folder);
end;
$$;


-- ###########################################################################
-- 7. MAINTENANCE — reconcile, report, never delete
-- ###########################################################################

-- Uploads that never reached `ready`:
--   * pending or failed, and the object IS there at the right size → finished
--     (the upload succeeded; only the finishing call was lost)
--   * pending, no object, older than document_pending_ttl() → failed, `expired`
-- Nothing is deleted. Returns how many rows it changed, by outcome.
create or replace function document_reconcile()
returns table (finished integer, expired integer)
  language plpgsql volatile security invoker set search_path = public as $$
declare
  d project_documents;
  outcome text;
  done_n integer := 0;
  expired_n integer := 0;
begin
  if not is_owner() then
    raise exception 'stratos:document_owner_only' using errcode = '42501';
  end if;
  for d in
    select * from project_documents
    where upload_state in ('pending', 'failed') and trashed_at is null
  loop
    if document_object_size(d.storage_path) is not null then
      outcome := document_finish_upload(d.id);
      if outcome = 'ready' then done_n := done_n + 1; end if;
    elsif d.upload_state = 'pending' and d.created_at < now() - document_pending_ttl() then
      update project_documents set upload_state = 'failed', failure_reason = 'expired' where id = d.id;
      expired_n := expired_n + 1;
    end if;
  end loop;
  return query select done_n, expired_n;
end;
$$;

-- What storage holds that the library does not account for, and the reverse.
-- A report for the owner to act on by hand in the Supabase dashboard:
--
--   orphan_object        an object in the bucket with no document row
--   missing_object       a finished document whose object is gone
--   unfinished_object    an object whose row is still pending/failed
--   changed_object       a finished document whose object is no longer the size
--                        it was finished at — replaced behind the library's back
--   trashed_object       a trashed document; its object still uses storage
create or replace function document_storage_report()
returns table (kind text, storage_path text, byte_size bigint, document_id uuid, document_name text)
  language sql stable security invoker set search_path = public as $$
  select 'orphan_object', o.name, (o.metadata->>'size')::bigint, null::uuid, null::text
  from storage.objects o
  where o.bucket_id = document_bucket() and is_owner()
    and not exists (select 1 from project_documents d where d.storage_path = o.name)
  union all
  select case
           when d.trashed_at is not null and o.name is not null then 'trashed_object'
           when d.upload_state = 'ready' and o.name is null then 'missing_object'
           when d.upload_state = 'ready' and (o.metadata->>'size')::bigint <> d.byte_size then 'changed_object'
           when d.upload_state <> 'ready' and o.name is not null then 'unfinished_object'
         end,
         d.storage_path, coalesce((o.metadata->>'size')::bigint, d.byte_size), d.id, d.name
  from project_documents d
  left join storage.objects o on o.bucket_id = document_bucket() and o.name = d.storage_path
  where (d.trashed_at is not null and o.name is not null)
     or (d.upload_state = 'ready' and o.name is null)
     or (d.upload_state = 'ready' and (o.metadata->>'size')::bigint <> d.byte_size)
     or (d.upload_state <> 'ready' and o.name is not null)
  order by 1, 2
$$;


-- ###########################################################################
-- 8. ACCESS
-- ###########################################################################

-- ------------------------------------------------------------ the tables
-- The owner, and nobody else, for every operation the grants allow. FORCE so
-- the table owner's own sessions are held to it too.
alter table document_folders  enable row level security;
alter table document_folders  force  row level security;
alter table project_documents enable row level security;
alter table project_documents force  row level security;

drop policy if exists document_folders_owner_all  on document_folders;
drop policy if exists project_documents_owner_all on project_documents;
create policy document_folders_owner_all on document_folders
  for all using (is_owner()) with check (is_owner());
create policy project_documents_owner_all on project_documents
  for all using (is_owner()) with check (is_owner());

-- Grants: read, create, change. Never DELETE — for anybody, the owner
-- included: there is no hard-delete path through the API. anon gets nothing.
do $$
declare
  f text;
begin
  execute 'revoke all on table document_folders, project_documents from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table document_folders, project_documents from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table document_folders, project_documents from authenticated';
    execute 'grant select, insert, update on table document_folders, project_documents to authenticated';
  end if;

  -- The functions: the owner's operations for `authenticated` (each answers to
  -- RLS, so a non-owner gets nothing done); nothing for anon.
  foreach f in array array[
    'document_object_size(text)',
    'document_lock(uuid)',
    'document_free_name(uuid, uuid, text, uuid, text)',
    'document_begin_upload(uuid, uuid, text, bigint, text, text)',
    'document_finish_upload(uuid)',
    'document_move(uuid, uuid)',
    'document_restore_folder_chain(uuid)',
    'document_restore(uuid)',
    'document_trash_folder(uuid)',
    'document_restore_folder(uuid)',
    'document_reconcile()',
    'document_storage_report()'
  ] loop
    execute format('revoke all on function %s from public', f);
    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke all on function %s from anon', f);
    end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then
      execute format('grant execute on function %s to authenticated', f);
    end if;
  end loop;
end $$;

-- ------------------------------------------------------------ the objects
-- Storage checks these policies with the caller's own JWT (`authenticated` +
-- `request.jwt.claims`), which is why `is_owner()` works here unchanged.
--
-- PERMISSIVE — what the owner may do in this bucket:
--   select   every object (signed download URLs, downloads, the report)
--   insert   ONLY at the path of a live `pending` document row. Creating a
--            signed upload URL runs this check, so each URL is for exactly one
--            document's path, and only while that row is waiting for its file.
-- There is no permissive UPDATE (so no upsert / overwrite) and no DELETE.
--
-- RESTRICTIVE — guards ANDed with every other policy on storage.objects, so a
-- broad policy written for some other bucket (or later, by hand) can never
-- open this one: in this bucket, select needs the owner, insert needs the owner
-- and a pending row, and update and delete are refused outright.
drop policy if exists project_documents_owner_select on storage.objects;
drop policy if exists project_documents_owner_insert on storage.objects;
drop policy if exists project_documents_guard_select on storage.objects;
drop policy if exists project_documents_guard_insert on storage.objects;
drop policy if exists project_documents_guard_update on storage.objects;
drop policy if exists project_documents_guard_delete on storage.objects;
-- Left by supabase/checks/documents-rollback.sql; re-applying this file lifts it.
drop policy if exists project_documents_sealed on storage.objects;

create policy project_documents_owner_select on storage.objects
  as permissive for select to authenticated
  using (bucket_id = 'project-documents' and public.is_owner());

create policy project_documents_owner_insert on storage.objects
  as permissive for insert to authenticated
  with check (
    bucket_id = 'project-documents'
    and public.is_owner()
    and exists (select 1 from public.project_documents d
                where d.storage_path = objects.name and d.upload_state = 'pending' and d.trashed_at is null)
  );

create policy project_documents_guard_select on storage.objects
  as restrictive for select
  using (bucket_id <> 'project-documents' or public.is_owner());

create policy project_documents_guard_insert on storage.objects
  as restrictive for insert
  with check (
    bucket_id <> 'project-documents'
    or (public.is_owner()
        and exists (select 1 from public.project_documents d
                    where d.storage_path = objects.name and d.upload_state = 'pending' and d.trashed_at is null))
  );

create policy project_documents_guard_update on storage.objects
  as restrictive for update
  using (bucket_id <> 'project-documents')
  with check (bucket_id <> 'project-documents');

create policy project_documents_guard_delete on storage.objects
  as restrictive for delete
  using (bucket_id <> 'project-documents');

-- ------------------------------------------------ no overwrite, by any path
-- The policies above cannot stop an overwrite on their own. Observed on a real
-- local Supabase (Storage 1.77, scripts/documents-live-check.mjs):
--   * `createSignedUploadUrl(path, { upsert: true })` IS issued for a pending
--     path — Storage checks only the INSERT policy when the link is made;
--   * the upload with that token runs as Storage's superuser, so no policy is
--     consulted, and with upsert it UPDATES the existing row — after the
--     document was finished, "hello" was replaced by other bytes.
-- So the rule is enforced below RLS: in this bucket a stored object's row can
-- never be updated. Storage writes the new bytes under a fresh version first
-- and deletes them when its database step fails, so the refused overwrite
-- leaves the original object and its bytes untouched (observed: the second PUT
-- answers 400 and the download still returns the original).
-- Nothing in the library ever needs to update an object: keys are generated,
-- there is no move, rename or replace of a stored file.
create or replace function document_object_immutable() returns trigger
  language plpgsql
  set search_path = public
as $$
begin
  if old.bucket_id = 'project-documents' or new.bucket_id = 'project-documents' then
    raise exception 'stratos:document_object_immutable'
      using errcode = '42501',
            hint = 'A stored document is never overwritten. Upload a new file instead.';
  end if;
  return new;
end;
$$;

drop trigger if exists project_documents_no_overwrite on storage.objects;
create trigger project_documents_no_overwrite
  before update on storage.objects
  for each row execute function document_object_immutable();
